#pragma once

// OpenGL function loader stub
// In a real implementation, this would be generated by glad
#ifdef __APPLE__
    #include <OpenGL/gl3.h>
    #include <OpenGL/gl3ext.h>
#else
    #include <GL/gl.h>
    #include <GL/glext.h>
#endif

// Initialize OpenGL function pointers (stub implementation)
inline int gladLoadGL() {
    return 1; // Success
} 